SOURCES_C += \
    $(CORE_DIR)/libretro/agb_fast_boot.c \
    $(CORE_DIR)/libretro/cgb_fast_boot.c \
    $(CORE_DIR)/libretro/dmg_fast_boot.c \
    $(CORE_DIR)/libretro/sgb_fast_boot.c \
    $(CORE_DIR)/libretro/sgb2_fast_boot.c
